In [1]:
import numpy as np

#numpy를 사용하기 위해 array 형태로 만들기
data1 = [1,2,3,4,5]
array1 = np.array(data1)
print(array1)

# array 의 크기와 형태 확인
array1.shape

[1 2 3 4 5]


(5,)

In [2]:
#numpy를 사용하기 위해 array 형태로 만들기
data2 = [1 , 2 , 3 , 4 , 5.5]
array2 = np.array(data2)
print(array2)

# array 의 크기와 형태 확인
array2.shape

[1.  2.  3.  4.  5.5]


(5,)

In [3]:
#numpy를 사용하기 위해 array 형태로 만들기
data3 = [1 , 2 , 3 , 4 , '새우깡']
array3 = np.array(data3)
print(array3)

# array 의 크기와 형태 확인
array3.shape

['1' '2' '3' '4' '새우깡']


(5,)

In [4]:
print('array1:',array1.dtype)
print('array2:',array2.dtype)
print('array3:',array3.dtype)

array1: int32
array2: float64
array3: <U11


In [5]:
array4 = np.array( [1,2,3,4,5])
print(array4)

[1 2 3 4 5]


In [6]:
# 2차원의 array 생성하기
array5 = np.array( [ [1,2,3],[3,4,5],[5,6,7] ])
print(array5)

array5.shape

[[1 2 3]
 [3 4 5]
 [5 6 7]]


(3, 3)

In [7]:
# array 산술연산하기
# 예제 데이터 생성하기

array1 = np.array( [ [1,2,3] , [4,5,6] ])
print(array1)

print("\n")

array2 = np.array( [ [10,20,30] , [40,50,60] ])
print(array2)

[[1 2 3]
 [4 5 6]]


[[10 20 30]
 [40 50 60]]


In [8]:
# array 산술연산
# 1. 덧셈

array1 + array2

array([[11, 22, 33],
       [44, 55, 66]])

In [9]:
# array 산술연산
# 2. 뺄셈

array2 - array1

array([[ 9, 18, 27],
       [36, 45, 54]])

In [10]:
# array 산술연산
# 3. 곱셈

array1 * array2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [11]:
# array 산술연산
# 4. 나눗셈

array2 / array1

array([[10., 10., 10.],
       [10., 10., 10.]])

In [12]:
# array 데이터 조회하기
# 1차원 array 조회하기
array1 = np.array([1,2,3,4,5])
print('전체값:' , array1)
print('1번째값:' , array1[0])
print('3번째값:' , array1[2])
print('2-4번째값:',array1[1:4])

전체값: [1 2 3 4 5]
1번째값: 1
3번째값: 3
2-4번째값: [2 3 4]


In [13]:
# array 데이터 조회하기
# 2차원 array 조회하기
array2 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(array2)
print('\n')
print(array2[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


9


In [14]:
# 예제 데이터 만들기
array1 = np.random.randn(3,3)
array1

array([[-0.19943576,  0.16067923,  0.2448111 ],
       [ 0.69465524,  0.53626504, -0.49505223],
       [ 1.37787998, -0.95326008, -1.34576086]])

In [15]:
import numpy as np

In [16]:
# abs( ) 함수 - 절대값 계산하기
np.abs(array1)

array([[0.19943576, 0.16067923, 0.2448111 ],
       [0.69465524, 0.53626504, 0.49505223],
       [1.37787998, 0.95326008, 1.34576086]])

In [17]:
# square( ) 함수 - 제곱값 계산하기
np.square(array1)

array([[0.03977462, 0.02581781, 0.05993247],
       [0.4825459 , 0.2875802 , 0.24507671],
       [1.89855323, 0.90870477, 1.81107229]])

In [18]:
# ceil( ) 함수 - 주어진 값보다 큰 가장 가까운 정수 찾기
np.ceil(array1)

array([[-0.,  1.,  1.],
       [ 1.,  1., -0.],
       [ 2., -0., -1.]])

In [19]:
# floor( ) 함수 - 주어진 값보다 작은 가장 가까운 정수 찾기
np.floor(array1)

array([[-1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 1., -1., -2.]])

In [20]:
# isnan( ) 함수 - 주어진 값의 NaN 여부를 찾는 함수
np.isnan(array1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [21]:
#isinf( ) 함수 - 주어진 값의 무한대 여부를 찾는 함수
np.isinf(array1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
# sort( ) 함수 - 오름차순 정렬 하기
np.sort(array1)

array([[-0.93238836, -0.40120009,  1.7544724 ],
       [-0.40007399, -0.30967648,  0.43033704],
       [-0.68097422, -0.44908935,  0.38095857]])

In [23]:
# 내림차순으로 정렬하기
np.sort(array1)[::1]

array([[-0.93238836, -0.40120009,  1.7544724 ],
       [-0.40007399, -0.30967648,  0.43033704],
       [-0.68097422, -0.44908935,  0.38095857]])

In [27]:
np.sort(array1)[::]

array([[-0.93238836, -0.40120009,  1.7544724 ],
       [-0.40007399, -0.30967648,  0.43033704],
       [-0.68097422, -0.44908935,  0.38095857]])

In [3]:
#Pandas ex_4
import pandas as pd

member=pd.Series(['홍길동','전우치','강감찬','스티브잡스'],
                index = ['1번','2번','3번','4번'])
member

1번      홍길동
2번      전우치
3번      강감찬
4번    스티브잡스
dtype: object

In [4]:
member['1번']

'홍길동'

In [5]:
member[ ['1번','3번'] ]

1번    홍길동
3번    강감찬
dtype: object

In [7]:
#pandas ex_5
sal_1 = {'일지매' : 130 , '전우치' : 120, '홍길동':100}
sal_2 = pd.Series(sal_1)
sal_2

일지매    130
전우치    120
홍길동    100
dtype: int64

In [8]:
sal_3 = {'홍길동' : 10 , '전우치' : 12, '강감찬':20}
sal_4 = pd.Series(sal_3)
sal_4

홍길동    10
전우치    12
강감찬    20
dtype: int64

In [9]:
print(sal_2 + sal_4)

강감찬      NaN
일지매      NaN
전우치    132.0
홍길동    110.0
dtype: float64


In [10]:
#Pandas ex_6
# 딕셔너리와 리스트를 활용하여 Data Frame 생성하기

member3 = {'번호' : ['1번','2번','3번'] ,
           '이름' : ['홍길동','전우치','강감찬'],
           '생년' : [1975 , 1980 , 1992] }
member4 = pd.DataFrame(member3)
member4 

번호   이름    생년
0  1번  홍길동  1975
1  2번  전우치  1980
2  3번  강감찬  1992

In [12]:
#Pandas ex_7
# 딕셔너리와 리스트를 활용하여 Data Frame 생성하기-컬럼이름순서 지정하기

member3 = {'번호' : ['1번','2번','3번'] ,
           '이름' : ['홍길동','전우치','강감찬'],
           '생년' : [1975 , 1980 , 1992] }
member5 = pd.DataFrame(member3 , columns=['번호','생년','이름'])
member5

번호    생년   이름
0  1번  1975  홍길동
1  2번  1980  전우치
2  3번  1992  강감찬

In [14]:
#pandas ex_7_2
no = ['1번','2번','3번']
name = ['홍길동','전우치','강감찬']
birth = [1975,1982,1980]

member6 = pd.DataFrame()
member6['번호'] = no
member6['이름'] = name
member6['생년'] = birth
member6

번호   이름    생년
0  1번  홍길동  1975
1  2번  전우치  1982
2  3번  강감찬  1980

In [18]:
member6.sort_values(['생년'] , ascending=[False])

번호   이름    생년
1  2번  전우치  1982
2  3번  강감찬  1980
0  1번  홍길동  1975

In [21]:
import pandas as pd

data1 = pd.read_excel('c:\\temp\\부품구입대장2.xls')
data1

신청날짜 사업장          품목  수량       단가        금액
0  2019-08-23  석수       ANGLE  21    32000    672000
1  2019-09-09  석수          백관  44    56000   2464000
2  2019-06-18  석수         절연판  40    45000   1800000
3  2019-03-13  석수  P/Z O-RING  11    38000    418000
4  2019-05-11  석수         알코올  38     8000    304000
5  2019-06-28  석수         실리콘  30   150000   4500000
6  2019-02-16  석수         소모품   4     2200      8800
7  2019-10-22  석수       MOTOR  14    30000    420000
8  2019-03-18  석수  PAPER BRSH  13    40000    520000
9  2019-07-17  석수        불화카리  23    83000   1909000
10 2019-07-23  석수         마크펜  33     3000     99000
11 2019-03-20  석수         NUT  20    15000    300000
12 2019-01-27  석수         윤활유  30  2000000  60000000
13 2019-07-11  석수         소모품  50     2200    110000
14 2019-05-16  석수        BITE  14    86000   1204000

In [22]:
# csv 파일 불러오기 - 인코딩 지정하기
import pandas as pd

data1 = pd.read_csv('c:\\temp\\사원별판매현황_홍길동.csv' ,
                   names = ['이름','요일','실적'] , encoding='cp949')
data1

이름   요일   실적
0   이름   요일   실적
1  홍길동  월요일  100
2  홍길동  화요일   70
3  홍길동  수요일   80
4  홍길동  목요일   85
5  홍길동  금요일   65
6  홍길동  토요일   95
7  홍길동  일요일  120

In [23]:
#data frame 에서 원하는 데이터 조회하기
member5

번호    생년   이름
0  1번  1975  홍길동
1  2번  1980  전우치
2  3번  1992  강감찬

In [25]:
member5['생년'] # 2개이상의 컬럼일 경우 member5[ ['이름','생년'] ]

0    1975
1    1980
2    1992
Name: 생년, dtype: int64

In [26]:
member5.loc[0]

번호      1번
생년    1975
이름     홍길동
Name: 0, dtype: object

In [27]:
member5.loc[ member5['번호'] >= '2']

번호    생년   이름
1  2번  1980  전우치
2  3번  1992  강감찬

In [28]:
member6 = {'번호' : [1,2,3,4,5] ,
           '이름' : ['홍길동','전우치','강감찬','일지매','을지문덕'],
           '매출' : [100,200,300,250,150]}
member7 = pd.DataFrame(member6 , columns=['번호','이름','매출'])
member7

번호    이름   매출
0   1   홍길동  100
1   2   전우치  200
2   3   강감찬  300
3   4   일지매  250
4   5  을지문덕  150

In [30]:
# 매출이 100 이상 ~ 200 이하인 행만 출력하기
member7.loc[ (member7['매출'] >= 100) & (member7['매출'] <= 200)]

번호    이름   매출
0   1   홍길동  100
1   2   전우치  200
4   5  을지문덕  150

In [31]:
# 매출이 100 이상 ~ 200 이하인 행의 이름컬럼과 매출 컬럼만 출력하기
member7.loc[ (member7['매출'] >= 100) & (member7['매출'] <= 200),['이름','매출'] ]

이름   매출
0   홍길동  100
1   전우치  200
4  을지문덕  150

In [36]:
# 매출이 150 이하 이거나 또는 300 이상인 행의 이름컬럼과 매출 컬럼만 출력하기
member7.loc[ (member7['매출'] <= 150) | (member7['매출'] >= 300),['이름','매출'] ]

이름   매출
0   홍길동  100
2   강감찬  300
4  을지문덕  150

In [38]:
# 새로운 열 추가하기
member8 = pd.DataFrame( member5 ,columns=['번호','이름','생년','지역'])
member8

번호   이름    생년  지역
0  1번  홍길동  1975 NaN
1  2번  전우치  1980 NaN
2  3번  강감찬  1992 NaN

In [39]:
member8['지역'] = ['서울','대전','강원']
member8

번호   이름    생년  지역
0  1번  홍길동  1975  서울
1  2번  전우치  1980  대전
2  3번  강감찬  1992  강원

In [41]:
# 새로운 행 추가하기
member8.loc[3] = ['4번','서진수',1975,'경기']
member8

번호   이름    생년  지역
0  1번  홍길동  1975  서울
1  2번  전우치  1980  대전
2  3번  강감찬  1992  강원
3  4번  서진수  1975  경기

In [48]:
# 행 삭제하기
member8

번호   이름    생년  지역
0  1번  홍길동  1975  서울
1  2번  전우치  1980  대전
2  3번  강감찬  1992  강원
3  4번  서진수  1975  경기

In [43]:
member8.drop( [0] )

번호   이름    생년  지역
1  2번  전우치  1980  대전
2  3번  강감찬  1992  강원
3  4번  서진수  1975  경기

In [52]:
# 특정 조건의 행 삭제하기
member8.drop( member8[ member8.생년 >= 1980].index )

번호   이름    생년  지역
0  1번  홍길동  1975  서울
3  4번  서진수  1975  경기

In [53]:
# 2개 이상의 특정 조건을 지정하여 특정 행 삭제하기
member8.drop( member8[ (member8.생년 >= 1980) | (member8.지역=='서울')].index )

번호   이름    생년  지역
3  4번  서진수  1975  경기